### ISSUE TITLE
原来能用，现在不能用了，提示如下错误

### ISSUE THREAD

**Issue by lzwhw2000** [waditu/tushare_matlab#1]
运行
df_basic = api.query('stock_basic')

提示如下错误
Response stream is undefined
 below is a Java Error dump (truncated):
抱歉：请检查网络设置.

**Comment by bathsurf** [comment]
我也想用matlab试一下，发现同样的问题，然后只能用tushare的http接口
代码供参考

clc;
clear all;

import matlab.net.* %倒入Matlab网络请求库
import matlab.net.http.*

uri = URI('http://api.waditu.com')

qStruct.api_name = 'stock_basic';
qStruct.token = '';  %此处填入token
qStruct.params.list_status = 'L';
qStruct.fields = '';

r = RequestMessage;
r.Method = 'POST';
r.Body = matlab.net.http.MessageBody(qStruct);

r = addFields(r,'Content-Type','application/json');


response = send(r,uri);%发送请求
status = response.StatusCode%获取服务器响应的状态码
if (status==200) %一般成功响应的状态码为200 表示ok 即成功
    content = response.Body.Data %获取服务器响应的内容
    disp('请求成功：')
    disp(content)
else
    disp('请求失败')
end

==============================
 希望能给加点积分呀

**Comment by jimmysoa** [comment]
并没有做任何修改，而且我刚确认是可以调取的，请确定网络是否有问题。

**Comment by lzwhw2000** [comment]
最近确实又可以了，不清楚哪儿的问题

**Comment by lzwhw2000** [comment]
> 我也想用matlab试一下，发现同样的问题，然后只能用tushare的http接口
> 代码供参考
> 
> clc;
> clear all;
> 
> import matlab.net.* %倒入Matlab网络请求库
> import matlab.net.http.*
> 
> uri = URI('http://api.waditu.com')
> 
> qStruct.api_name = 'stock_basic';
> qStruct.token = ''; %此处填入token
> qStruct.params.list_status = 'L';
> qStruct.fields = '';
> 
> r = RequestMessage;
> r.Method = 'POST';
> r.Body = matlab.net.http.MessageBody(qStruct);
> 
> r = addFields(r,'Content-Type','application/json');
> 
> response = send(r,uri);%发送请求
> status = response.StatusCode%获取服务器响应的状态码
> if (status==200) %一般成功响应的状态码为200 表示ok 即成功
> content = response.Body.Data %获取服务器响应的内容
> disp('请求成功：')
> disp(content)
> else
> disp('请求失败')
> end
> 
> ==============================
> 希望能给加点积分呀

在matlab中出现这个错误，这几个函数是怎么回事？

未定义函数或变量 'URI'
未定义函数或变量 'RequestMessage'
